class elem():
    regis_btn = "[class=ico-register]"
    radio_male_btn = "[id=gender-male]"
    radio_female_btn = "[id=gender-female]"
    fname = "[id=FirstName]"
    lsaname = "[id=LastName]"
    email = "[id=Email]"
    password = "[id=Password]"
    cpassword = "[id=ConfirmPassword]"
    regis2_btn = "[id=register-button]"
    errormsg_regis = "[class=field-validation-valid]"
    titlewolcome = "[class=page-title]"
    login_btn = "[class=ico-login]"
    emaillogin = "[id=Email]"
    passwordlogin = "[id=Password]"
    radio_remember_btn = "[id=RememberMe]"
    login2_btn = "[class=button-1 login-button]"
    errormsg_login = "[class=validation-summary-errors]"
    titlestore = "[class=topic-html-content-header]"
    addchart_btn = "[class=button-2 product-box-add-to-cart-button]"
    reciptname = "[id=giftcard_2_RecipientName]"
    reciptemail = "[id=giftcard_2_RecipientEmail]"
    yourname = "[id=giftcard_2_SenderName]"
    youremail = "[id=giftcard_2_SenderEmail]"
    addchart2_btn = "[id=add-to-cart-button-2]"
    content = "[class=content]"